spring.application.name=FashionStore

spring.jpa.open-in-view=false
spring.profiles.active=dev
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED:false}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:false}

app.jwt.secret=${APP_JWT_SECRET}
app.jwt.access-token-ttl-minutes=15
app.jwt.refresh-token-ttl-days=7
